Added preliminary support for running GitHub actions locally.

diff --git a/.github/workflows/build-app.yml b/.github/workflows/build-app.yml
--- a/.github/workflows/build-app.yml
+++ b/.github/workflows/build-app.yml
@@ -17,7 +17,7 @@ on:
 
 defaults:
   run:
-    shell: bash --noprofile --norc -x -euo pipefail {0}
+    shell: /tmp/gh-sh {0}
 
 jobs:
   build-app:
@@ -44,9 +44,23 @@ jobs:
       APP_STORE_AUTHENTICATION_KEY_BASE64: ${{ secrets.APP_STORE_AUTHENTICATION_KEY_BASE64 }}
       APP_STORE_AUTHENTICATION_KEY_ID: ${{ secrets.APP_STORE_AUTHENTICATION_KEY_ID }}
       APP_STORE_AUTHENTICATION_KEY_ISSUER_ID: ${{ secrets.APP_STORE_AUTHENTICATION_KEY_ISSUER_ID }}
+      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+      KEYCHAIN_NAME: app-signing.keychain-db
 
     steps:
+      - name: ACT preamble
+        shell: bash --noprofile --norc -x -euo pipefail {0}
+        run: |
+          if [ z"${ACT:-}" == z"true" ]; then
+            ./GHALocal/bin/gh-runner-host-preamble
+          else
+            echo '#!/bin/bash --noprofile --norc -x -euo pipefail' > /tmp/gh-sh
+            echo 'source "$@"' >> /tmp/gh-sh
+            chmod +x /tmp/gh-sh
+          fi
+
       - name: Dump GitHub Action Properties
+        if: ${{ !env.ACT }}
         run: |
           echo "github.event_name: ${{ github.event_name }}"
           echo "github.event.inputs.build-config: ${{ github.event.inputs.build-config }}"
@@ -67,12 +81,12 @@ jobs:
         if: ${{ matrix.build-config.if }}
         run: |
           echo 'PRODUCT_NAME=${{ matrix.run-config.scheme }}' >> $GITHUB_ENV
-          echo 'DERIVED_DATA_PATH=${{ runner.temp }}/build.derivedData' >> $GITHUB_ENV
-          echo 'EXPORT_PATH=${{ runner.temp }}/build.export' >> $GITHUB_ENV
-          echo 'AUTHENTICATION_KEY_PATH=${{ runner.temp }}/authentication.p8' >> $GITHUB_ENV
+          echo "DERIVED_DATA_PATH=$RUNNER_TEMP/build.derivedData" >> $GITHUB_ENV
+          echo "EXPORT_PATH=$RUNNER_TEMP/build.export" >> $GITHUB_ENV
+          echo "AUTHENTICATION_KEY_PATH=$RUNNER_TEMP/authentication.p8" >> $GITHUB_ENV
 
       - uses: maxim-lobanov/setup-xcode@v1.4.1
-        if: ${{ matrix.build-config.if }}
+        if: ${{ matrix.build-config.if && !env.ACT }}
         with:
           xcode-version: '13.4'
 
@@ -98,7 +112,7 @@ jobs:
           KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
         run: |
           # create variables
-          KEYCHAIN_PATH="$RUNNER_TEMP"/app-signing.keychain-db
+          KEYCHAIN_PATH="$RUNNER_TEMP"/"$KEYCHAIN_NAME"
 
           # create temporary keychain
           security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
@@ -148,13 +162,18 @@ jobs:
             ${{ runner.os }}-spm-
 
       - name: XcodeGen
-        if: ${{ matrix.build-config.if }}
+        if: ${{ matrix.build-config.if && !env.ACT }}
         uses: grigorye/xcodegen-action@feature/projectRoot
         with:
           spec: XcodeGen/Variant/${{ matrix.build-config.projectKind }}.yml
           project: Xcodeproj
           project-root: .
           version: '2.26.0'
+
+      - name: XcodeGen
+        if: ${{ env.ACT }}
+        run: |
+          /usr/local/bin/mint run xcodegen -s XcodeGen/Variant/${{ matrix.build-config.projectKind }}.yml -r . -p Xcodeproj
 
       - name: Build .xcarchive
         if: ${{ matrix.build-config.if }}
@@ -176,6 +195,12 @@ jobs:
             BUNDLE_VERSION="$BUNDLE_VERSION" \
             | xcpretty
           ./GHAShortcuts/gh-tar "$(dirname "$ARCHIVE_PATH")" "$ARCHIVE_PATH"
+
+      - name: Pull .xcarchive
+        if: ${{ matrix.build-config.if && env.ACT }}
+        shell: bash --noprofile --norc -x -euo pipefail {0}
+        run: |
+          scp -pr "$REMOTE_RUNNER_USER"@host.docker.internal:"$ARCHIVE_PATH".tar "$ARCHIVE_PATH".tar
 
       - name: Save .xcarchive
         if: ${{ matrix.build-config.if }}
@@ -214,6 +239,12 @@ jobs:
               -format UDZO \
               "$DMG_PATH"
 
+      - name: Pull .dmg
+        if: ${{ matrix.build-config.if && matrix.build-config.name == 'DeveloperID' && env.ACT }}
+        shell: bash --noprofile --norc -x -euo pipefail {0}
+        run: |
+          scp -pr "$REMOTE_RUNNER_USER"@host.docker.internal:"$DMG_PATH" "$DMG_PATH"
+          
       - name: Save .dmg
         if: ${{ matrix.build-config.if && matrix.build-config.name == 'DeveloperID' }}
         uses: actions/upload-artifact@v2
@@ -224,7 +255,7 @@ jobs:
             ${{ env.DMG_PATH }}
 
       - name: Upload to TestFlight
-        if: ${{ matrix.build-config.if && matrix.build-config.name == 'AppStore' }}
+        if: ${{ matrix.build-config.if && matrix.build-config.name == 'AppStore' && !env.ACT }}
         run: |
           # create variables
           API_KEY_NAME="$APP_STORE_AUTHENTICATION_KEY_ID"
@@ -245,3 +276,9 @@ jobs:
             --file "$EXPORT_PATH"/*${{ matrix.run-config.packageExtension }} \
             --apiKey "$API_KEY_NAME" \
             --apiIssuer "$APP_STORE_AUTHENTICATION_KEY_ISSUER_ID"
+
+      - name: ACT epilogue
+        if: ${{ env.ACT && always() }}
+        shell: bash --noprofile --norc -x -euo pipefail {0}
+        run: |
+          ./GHALocal/bin/gh-runner-host-epilogue
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -9,7 +9,7 @@ on:
 
 defaults:
   run:
-    shell: bash --noprofile --norc -x -euo pipefail {0}
+    shell: /tmp/gh-sh {0}
 
 jobs:
   tests:
@@ -19,8 +19,21 @@ jobs:
     env:
       PROJECT_KIND: 'DeveloperID'
       RUN_STAMP: ${{ github.run_id }}.${{ github.run_attempt }}
+      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+      KEYCHAIN_NAME: app-signing.keychain-db
 
     steps:
+      - name: ACT preamble
+        shell: bash --noprofile --norc -x -euo pipefail {0}
+        run: |
+          if [ z"${ACT:-}" == z"true" ]; then
+            ./GHALocal/bin/gh-runner-host-preamble
+          else
+            echo '#!/bin/bash --noprofile --norc -x -euo pipefail' > /tmp/gh-sh
+            echo 'source "$@"' >> /tmp/gh-sh
+            chmod +x /tmp/gh-sh
+          fi
+
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
@@ -33,11 +46,12 @@ jobs:
 
       - name: Setup Environment
         run: |
-          echo 'DERIVED_DATA_PATH=${{ runner.temp }}/build.derivedData' >> $GITHUB_ENV
-          echo 'XCRESULTS_DIRECTORY=${{ runner.temp }}' >> $GITHUB_ENV
-          echo 'REGENERATED_SNAPSHOTS_ARCHIVE=${{ runner.temp }}/Regenerated-Snapshots.${{ env.RUN_STAMP }}.tar.gz' >> $GITHUB_ENV
+          echo "DERIVED_DATA_PATH=$RUNNER_TEMP/build.derivedData" >> $GITHUB_ENV
+          echo "XCRESULTS_DIRECTORY=$RUNNER_TEMP" >> $GITHUB_ENV
+          echo "REGENERATED_SNAPSHOTS_ARCHIVE=$RUNNER_TEMP/Regenerated-Snapshots.${{ env.RUN_STAMP }}.tar.gz" >> $GITHUB_ENV
 
       - uses: maxim-lobanov/setup-xcode@v1.4.1
+        if: ${{ !env.ACT }}
         with:
           xcode-version: '13.4'
 
@@ -46,7 +60,7 @@ jobs:
           KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
         run: |
           # create variables
-          KEYCHAIN_PATH="$RUNNER_TEMP"/app-signing.keychain-db
+          KEYCHAIN_PATH="$RUNNER_TEMP"/"$KEYCHAIN_NAME"
 
           # create temporary keychain
           security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
@@ -94,12 +108,18 @@ jobs:
             ${{ runner.os }}-spm-
 
       - name: XcodeGen
+        if: ${{ !env.ACT }}
         uses: grigorye/xcodegen-action@feature/projectRoot
         with:
           spec: XcodeGen/Variant/${{ env.PROJECT_KIND }}.yml
           project: Xcodeproj
           project-root: .
           version: '2.26.0'
+      
+      - name: XcodeGen
+        if: ${{ env.ACT }}
+        run: |
+          /usr/local/bin/mint run xcodegen -s XcodeGen/Variant/${{ env.PROJECT_KIND }}.yml -r . -p Xcodeproj
 
       - name: Build All
         run: |
@@ -157,6 +177,12 @@ jobs:
           testExitCode=$(cat "$XCRESULTS_DIRECTORY"/TMBuddySnapshots.exit-code)
           [ "$testExitCode" -eq 0 ] || [ "$testExitCode" -eq 65 ] || exit "$testExitCode"
 
+      - name: Pull .xcresult for Snapshots
+        if: ${{ env.ACT }}
+        shell: bash --noprofile --norc -x -euo pipefail {0}
+        run: |
+          scp -pr "$REMOTE_RUNNER_USER"@host.docker.internal:"$SNAPSHOTS_XCRESULT".tar "$SNAPSHOTS_XCRESULT".tar
+          
       - name: Save .xcresult for Snapshots
         uses: actions/upload-artifact@v2
         with:
@@ -183,6 +209,12 @@ jobs:
           [ "$testExitCode" -eq 65 ] || exit "$testExitCode"
           find . -name '*.png' -newer "$stamp" -print0 | xargs -0 tar czf "$REGENERATED_SNAPSHOTS_ARCHIVE"
       
+      - name: Pull Regenerated Snapshots
+        if: ${{ env.ACT }}
+        shell: bash --noprofile --norc -x -euo pipefail {0}
+        run: |
+          scp "$REMOTE_RUNNER_USER"@host.docker.internal:"$REGENERATED_SNAPSHOTS_ARCHIVE" "$REGENERATED_SNAPSHOTS_ARCHIVE"
+
       - name: Save Regenerated Snapshots
         uses: actions/upload-artifact@v2
         with:
@@ -195,3 +227,9 @@ jobs:
         run: |
           testExitCode=$(cat "$XCRESULTS_DIRECTORY"/TMBuddySnapshots.exit-code)
           exit "$testExitCode"
+
+      - name: ACT epilogue
+        if: ${{ env.ACT && always() }}
+        shell: bash --noprofile --norc -x -euo pipefail {0}
+        run: |
+          ./GHALocal/bin/gh-runner-host-epilogue
